language: php

php:
  - 5.4
  - 5.5
  - 5.6
#  - 7.0

#matrix:
#  allow_failures:
#    - php: 7.0

services:
  - mongodb

before_script:
  - npm install -g bower
  - ln -s $(which bower) bin/bower
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - export SYMFONY_ENV=test
  - composer install --optimize-autoloader --prefer-source
  - php app/console --env=test doctrine:mongodb:schema:create --index
  - php app/console --env=test doctrine:mongodb:fixtures:load --append

script: phpunit --repeat=3 -c app/phpunitTravis.xml

after_script:
  - CODECLIMATE_REPO_TOKEN="7c5ee913b1deff0f89031388f37bac8d6c61077536e2367a1ed5345e37fd96fa" bin/test-reporter --stdout > codeclimate.json
  - cat codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/162920b9399e54be89a4
    on_success: always
    on_failure: always
    on_start: false