language: php

php:
  - 5.4
  - 5.5
  - 5.6
#  - 7.0

env:
  global:
    - SYMFONY_ENV=test
    - CODECLIMATE_URL="https://codeclimate.com/github/renatomefidf/sammui"

#matrix:
#  allow_failures:
#    - php: 7.0

services:
  - mongodb

before_script:
  - sh -c "Testing env, php is now $php"
  - npm install -g bower
  - ln -s $(which bower) bin/bower
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --optimize-autoloader --prefer-source
  - php app/console --env=test doctrine:mongodb:schema:create --index
  - php app/console --env=test doctrine:mongodb:fixtures:load --append

script: phpunit --repeat=3 -c app/phpunitTravis.xml

after_script: >
  bin/test-reporter -t 7c5ee913b1deff0f89031388f37bac8d6c61077536e2367a1ed5345e37fd96fa
  && curl -d message="[CodeClimate]($CODECLIMATE_URL) updated" https://webhooks.gitter.im/e/5b3b4bde928dc1451089
  || curl -d message="CodeClimate failed to update" -d level=error https://webhooks.gitter.im/e/5b3b4bde928dc1451089

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/162920b9399e54be89a4
    on_success: always
    on_failure: always