language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - mongodb

before_script:
  - npm install -g bower
  - ln -s $(which bower) bin/bower
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - export SYMFONY_ENV=test
  - composer install --optimize-autoloader --prefer-source
  - php app/console --env=test doctrine:mongodb:schema:create --index
  - php app/console --env=test doctrine:mongodb:fixtures:load --append

script: phpunit -c app --coverage-text

matrix:
  allow_failures:
    - php: 7.0