language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
  - npm install -g bower
  - ln -s $(which bower) bin/bower
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --dev --optimize-autoloader --prefer-source
  - php app/console --env=test doctrine:mongodb:schema:create --index
  - php app/console --env=test doctrine:mongodb:fixtures:load --append

script: phpunit -c app --coverage-text
