language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
  - npm install -g bower
  - echo which bower
  - ln -s $(which bower) bin/bower
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install

script: phpunit -c app --coverage-text
