mefi_form_rest:
    type:     rest
    resource: "@FormBundle/Resources/config/routing_rest.yml"
    prefix:   /form

mefi_user:
    resource: "@UserBundle/Resources/config/routing_rest.yml"
    prefix:   /api/user

mefi_api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

mefi_translate:
    resource: "@TranslateBundle/Resources/config/routing.yml"
    prefix:   /l10n

mefi_translate_rest:
    type:     rest
    resource: "@TranslateBundle/Resources/config/routing_rest.yml"
    prefix:   /l10n

flyers_frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

flyers_backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

# FOSAuthServerBundle
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
#fos_user
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile