services:
    api.oauth_client_extension:
        class: Renatomefi\ApiBundle\Twig\OAuthClientExtension
        arguments: [@fos_oauth_server.client_manager.default]
        tags:
            - { name: twig.extension }
    api.oauth_logout_success:
        class: Renatomefi\ApiBundle\OAuth\LogoutSuccess
        arguments: [@fos_oauth_server.access_token_manager, @fos_oauth_server.refresh_token_manager, @security.http_utils]